import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { Info } from '../TreeView/Icons';

/**
 * GUI widget that provides the user with information regarding a particular
 * object detection algorithm
 */
class MetaData extends Component {
    constructor(props){
        super(props);
        this.state = {
            slashLineStyle: {
                fontFamily: 'Noto Sans JP Black',
                color: '#367FFF',
                display: 'inline-block'
            },
            spanHeadStyle: {
                fontFamily: 'Noto Sans JP Medium'
            },
            spanBodyStyle: {
                fontFamily: 'Noto Sans JP Regular',
            },
            paragraphStyle: {
                margin: '0.6rem 0.6rem 0.6rem 0.6rem',
                display: 'inline-block',
                fontSize: '14',
                color: 'white'
            },
            divStyle: {
                paddingLeft: '1rem',
                paddingRight: '1rem',
                position: 'fixed',
                top: '5rem',
                left: '30%',
                backgroundColor: 'rgba(38, 38, 38, 0.5)',
                borderRadius: '1.375rem',
                justifyContent: 'center',
                textAlign: 'left',
                color: '#ffffff',
                width: 'max-content',
                height: '2.8125rem',
                
            },
        }
        this.onPrevAlgBtnClicked = this.onPrevAlgBtnClicked.bind(this);
        this.onNextAlgBtnClicked = this.onNextAlgBtnClicked.bind(this);
    }

    static propTypes = {
        isVisible: PropTypes.bool,
        detectorType: PropTypes.string,
        detectorConfigType: PropTypes.string,
        seriesType: PropTypes.string,
        studyType: PropTypes.string
    }

    /**
     * onPrevAlgBtnClicked - Method invoked when users tap the previous button (the one with the left arrow icon)
     *                     - The methods asks the App to load data that was generated by the previous algorithm
     * @return {type}  None
     */
    onPrevAlgBtnClicked(){
      if (this.props.prevAlgBtnEnabled){
        this.props.navigationBtnClick(-1);
      }
    }

    /**
     * onNextAlgBtnClicked - Method invoked when users tap the next button (the one with the right arrow icon)
     *                     - The methods asks the App to load data that was generated by the next algorithm
     * @return {type}  None
     */
    onNextAlgBtnClicked(){
      if (this.props.nextAlgBtnEnabled){
        this.props.navigationBtnClick(1);
      }
    }

    render() {
        if (!this.props.isVisible) return (<div></div>);
        return (
            <div style={this.state.divStyle}>
                <Info style={{verticalAlign: 'text-top'}} />
               <p style={this.state.paragraphStyle}>
                   <span style={this.state.spanHeadStyle}>Detector Type:</span>
                    <span style={this.state.spanBodyStyle}> {this.props.detectorType}</span>
                </p>
                <p style={this.state.slashLineStyle}>/</p>
               <p style={this.state.paragraphStyle}>
                   <span style={this.state.spanHeadStyle}>Detector Configuration:</span>
                    <span style={this.state.spanBodyStyle}> {this.props.detectorConfigType}</span>
                </p>
                <p style={this.state.slashLineStyle}>/</p>
               <p style={this.state.paragraphStyle}>
                   <span style={this.state.spanHeadStyle}>Series:</span>
                   <span style={this.state.spanBodyStyle}> {this.props.seriesType}</span>
                </p>
                <p style={this.state.slashLineStyle}>/</p>
               <p style={this.state.paragraphStyle}>
                   <span style={this.state.spanHeadStyle}>Study:</span>
                   <span style={this.state.spanBodyStyle}> {this.props.studyType}</span>
                </p>
            </div>
        );
    }
}

export default MetaData;
